FROM php:8.1-apache

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

RUN apt-get update \
    && apt-get install -qq -y --no-install-recommends \
    cron \
     vim \
     locales coreutils apt-utils git libicu-dev g++ libpng-dev libxml2-dev libzip-dev libonig-dev libxslt-dev;

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
   mv composer.phar /usr/local/bin/composer

RUN docker-php-ext-configure intl
RUN docker-php-ext-install  pdo mysqli pdo_mysql zip
#    pdo pdo_mysql mysqli gd opcache intl zip calendar dom mbstring zip gd xsl && a2enmod rewrite
#RUN pecl install apcu && docker-php-ext-enable apcu

#ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
#
#RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
#    install-php-extensions amqp

COPY .docker/server/apache/sites-enabled/apache.conf /etc/apache2/sites-enabled/000-default.conf
COPY .docker/server/php/entrypoint.sh /var/www/.docker/server/php/entrypoint.sh

CMD ["apache2-foreground"]

RUN chmod +x /var/www/.docker/server/php/entrypoint.sh

WORKDIR /var/www

ENTRYPOINT [".docker/server/php/entrypoint.sh"]





#FROM php:8.1-apache
#
#RUN a2enmod rewrite
#
#RUN apt-get update \
#  && apt-get install -y libzip-dev git wget --no-install-recommends \
#  && apt-get clean \
#  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
#
#RUN docker-php-ext-install pdo mysqli pdo_mysql zip;
#
#RUN wget https://getcomposer.org/download/2.5.8/composer.phar \
#    && mv composer.phar /usr/bin/composer && chmod +x /usr/bin/composer
#
#COPY .docker/apache.conf /etc/apache2/sites-enabled/000-default.conf
#COPY . /var/www
#
#WORKDIR /var/www
#
#CMD ["apache2-foreground"]
#
#RUN ["chmod", "755", "/var/www/.docker/entrypoint.sh"]
#
#ENTRYPOINT [".docker/entrypoint.sh"]

##RUN composer install
##EXPOSE 8000
##CMD php bin/console server:run 0.0.0.0:8000
